# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
FINNHUB_API_KEY = "d1psdrpr01qku4u4dhngd1psdrpr01qku4u4dho0"
NEWS_API_KEY = "723c9cc512784526a0fa28675e5bb04e"
