# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
FINNHUB_API_KEY = "d1psdrpr01qku4u4dhngd1psdrpr01qku4u4dho0"
NEWS_API_KEY = "723c9cc512784526a0fa28675e5bb04e"
